import { describe, expect, it, vi } from 'vitest';
import { LegacyShipFactory } from '../src/legacy/LegacyShipFactory';
import { LegacyShipComponentFactory } from '../src/legacy/LegacyShipComponentFactory';
import { legacyShipConfigSchema } from '../src/legacy/legacyShipConfig';
import { ShipFactory } from '../src/entities/ShipFactory';
import { ShipComponentFactory } from '../src/entities/ShipComponentFactory';
import { Ship } from '../src/entities/Ship';
import { DesignedShip } from '../src/entities/DesignedShip';
import { CargoType, EngineType, EquipmentType, PowerSourceType } from '../src/entities/interfaces/ShipComponents';
import { calculateShipStats, createDesign, designSchema, type ShipDesign } from '../src/domain/shipDesign';
import { createCivilianDesign } from '../src/domain/civilianPresets';
import { CombatShipFactory } from '../src/entities/CombatShipFactory';
import { ShipDesignManager } from '../src/utils/ShipDesignManager';

// Independent pre-boundary numerical contract, not generated by the implementation under test.
const powers = [
  { type: PowerSourceType.SOLAR, name: 'Солнечные панели', cost: 1000, weight: 50, capacity: 100, output: 5 },
  { type: PowerSourceType.NUCLEAR, name: 'Ядерный реактор', cost: 5000, weight: 200, capacity: 500, output: 20 },
  { type: PowerSourceType.FUSION, name: 'Термоядерный реактор', cost: 15000, weight: 300, capacity: 1500, output: 50 }
];
const engines = [
  { type: EngineType.CHEMICAL, name: 'Химический двигатель', cost: 800, weight: 100, thrust: 50, consumption: 2, speed: 100 },
  { type: EngineType.ION, name: 'Ионный двигатель', cost: 3000, weight: 150, thrust: 100, consumption: 5, speed: 200 },
  { type: EngineType.PLASMA, name: 'Плазменный двигатель', cost: 10000, weight: 250, thrust: 250, consumption: 15, speed: 400 }
];
const holds = [
  { type: CargoType.BASIC, name: 'Базовый грузовой отсек', cost: 500, weight: 80, volume: 100, capacity: 50 },
  { type: CargoType.REINFORCED, name: 'Укрепленный грузовой отсек', cost: 2000, weight: 150, volume: 250, capacity: 150 },
  { type: CargoType.ADVANCED, name: 'Продвинутый грузовой отсек', cost: 8000, weight: 200, volume: 500, capacity: 300 },
  { type: CargoType.CAPITAL, name: 'Тяжёлый грузовой отсек', cost: 12000, weight: 300, volume: 750, capacity: 450 }
];
const combinations = powers.flatMap(power => engines.flatMap(engine => holds.map(hold => ({ power, engine, hold }))));
const makeLegacy = () => LegacyShipFactory.createCustomShip('Legacy', PowerSourceType.SOLAR, EngineType.ION, CargoType.BASIC);

describe('explicit legacy factory boundary', () => {
  it.each(combinations)('preserves $power.type / $engine.type / $hold.type through both APIs', ({ power, engine, hold }) => {
    for (const factory of [LegacyShipFactory, ShipFactory]) {
      const ship = factory.createCustomShip('  Старое имя  ', power.type, engine.type, hold.type);
      expect(ship).toBeInstanceOf(Ship);
      expect(ship).not.toBeInstanceOf(DesignedShip);
      expect(ship.getDesign()).toBeUndefined();
      expect(ship.name).toBe('  Старое имя  ');
      expect(ship.powerSource).toEqual({ name: power.name, cost: power.cost, weight: power.weight,
        energyCapacity: power.capacity, energyOutput: power.output, currentEnergy: power.capacity });
      expect(ship.engine).toEqual({ name: engine.name, cost: engine.cost, weight: engine.weight,
        thrust: engine.thrust, energyConsumption: engine.consumption, maxSpeed: engine.speed });
      expect(ship.cargoHold).toEqual({ name: hold.name, cost: hold.cost, weight: hold.weight,
        capacity: hold.volume, maxWeight: hold.capacity, usedSpace: 0, currentWeight: 0 });
      const mass = power.weight + engine.weight + hold.weight;
      expect(ship.getTotalWeight()).toBe(mass);
      expect(ship.getTotalCost()).toBe(power.cost + engine.cost + hold.cost);
      expect(ship.getCurrentMaxSpeed()).toBeCloseTo(engine.speed * engine.thrust / (engine.thrust + mass * 0.1));
      expect(ship.getAvailableCargoSlots()).toBe(Math.floor(hold.volume / 10));
      expect(ship.getState()).toMatchObject({ energy: power.capacity, hull: 0, shield: 0, cargo: [], weapons: [] });
      expect(ship.equipment).toEqual([]);
    }
  });

  it.each(['', '   ', 'x'.repeat(81), null, 4])('rejects invalid names %j before building components', name => {
    const power = vi.spyOn(LegacyShipComponentFactory, 'createPowerSource');
    expect(() => ShipFactory.createCustomShip(name as string, PowerSourceType.SOLAR, EngineType.ION, CargoType.BASIC)).toThrow();
    expect(power).not.toHaveBeenCalled();
  });

  it.each(['unknown', 'constructor', '__proto__', 'toString', null, 0, {}])('rejects invalid enum selectors %j without partial construction', invalid => {
    const power = vi.spyOn(LegacyShipComponentFactory, 'createPowerSource');
    expect(() => ShipFactory.createCustomShip('Test', invalid as PowerSourceType, EngineType.ION, CargoType.BASIC)).toThrow();
    expect(() => ShipFactory.createCustomShip('Test', PowerSourceType.SOLAR, invalid as EngineType, CargoType.BASIC)).toThrow();
    expect(() => ShipFactory.createCustomShip('Test', PowerSourceType.SOLAR, EngineType.ION, invalid as CargoType)).toThrow();
    expect(power).not.toHaveBeenCalled();
  });

  it('keeps legacy selector validation separate from canonical persistence', () => {
    const config = { name: 'Legacy', powerSourceType: PowerSourceType.SOLAR, engineType: EngineType.ION, cargoType: CargoType.BASIC };
    expect(legacyShipConfigSchema.parse(config)).toEqual(config);
    expect(legacyShipConfigSchema.safeParse({ ...config, hullId: 'fighter' }).success).toBe(false);
    expect(designSchema.safeParse(config).success).toBe(false);
    const writes = vi.fn();
    const repository = new ShipDesignManager({ getItem: () => null, setItem: writes });
    expect(() => repository.saveDesign(makeLegacy() as unknown as ShipDesign)).toThrow();
    expect(writes).not.toHaveBeenCalled();
  });

  it('preserves energy, movement, cargo operations and independent compatibility instances', () => {
    const ship = makeLegacy(), other = makeLegacy();
    const module = ShipComponentFactory.createEquipment(EquipmentType.SCANNER);
    expect(ship.installEquipment(module)).toBe(true);
    expect(ship.loadCargo({ resourceType: 'ore', amount: 10, weight: 40, volume: 100 })).toBe(true);
    expect(ship.cargoHold.currentWeight).toBe(50);
    expect(ship.loadCargo({ resourceType: 'ore', amount: 1, weight: 1, volume: 1 })).toBe(false);
    expect(ship.consumeEnergy(50)).toBe(true);
    ship.startMoving(10, 0);
    const speed = ship.getCurrentMaxSpeed();
    ship.update(1);
    expect(ship.position.x).toBeCloseTo(speed);
    expect(ship.getState().energy).toBe(50); // Solar +5, ion -5: original recharge semantics.
    expect(other.getState().energy).toBe(100);
    expect(other.getState().cargo).toEqual([]);
    expect(other.equipment).toEqual([]);
    expect(ship.unloadCargo('ore', 10)).toBe(true);
    expect(ship.uninstallEquipment(module.id)).toBe(true);
    expect(ship.getTotalWeight()).toBe(280);
  });

  it('uses the same factory and ID sequence at both component import paths', () => {
    expect(ShipComponentFactory).toBe(LegacyShipComponentFactory);
    vi.spyOn(Date, 'now').mockReturnValue(123);
    const ids = new Set<string>();
    for (let i = 0; i < 20; i++) {
      ids.add(ShipComponentFactory.createEquipment(EquipmentType.WEAPON).id);
      ids.add(LegacyShipComponentFactory.createEquipment(EquipmentType.WEAPON).id);
      ids.add(makeLegacy().id);
      ids.add(ShipFactory.createCustomShip('Compat', PowerSourceType.SOLAR, EngineType.ION, CargoType.BASIC).id);
    }
    expect(ids.size).toBe(80);
  });

  it('returns independent catalogues and preserves their historical order', () => {
    expect(ShipComponentFactory.getAllPowerSources().map(item => item.name)).toEqual(powers.map(item => item.name));
    expect(ShipComponentFactory.getAllEngines().map(item => item.name)).toEqual(engines.map(item => item.name));
    expect(ShipComponentFactory.getAllCargoHolds().map(item => item.name)).toEqual(holds.map(item => item.name));
    ShipComponentFactory.getAllPowerSources()[0].energyOutput = 999;
    ShipComponentFactory.getAllEngines()[0].thrust = 999;
    ShipComponentFactory.getAllCargoHolds()[0].capacity = 999;
    const first = ShipComponentFactory.createEquipment(EquipmentType.MINING);
    first.effect!.miningSpeed = 999;
    expect(makeLegacy().powerSource.energyOutput).toBe(5);
    expect(ShipComponentFactory.getAllEngines()[0].thrust).toBe(50);
    expect(ShipComponentFactory.getAllCargoHolds()[0].capacity).toBe(100);
    expect(ShipComponentFactory.createEquipment(EquipmentType.MINING).effect!.miningSpeed).toBe(10);
  });
});

describe('legacy component input validation', () => {
  it.each(['constructor', '__proto__', 'toString', '', null, 1])('rejects invalid direct component kinds %j', invalid => {
    expect(() => ShipComponentFactory.createPowerSource(invalid as PowerSourceType)).toThrow();
    expect(() => ShipComponentFactory.createEngine(invalid as EngineType)).toThrow();
    expect(() => ShipComponentFactory.createCargoHold(invalid as CargoType)).toThrow();
    expect(() => ShipComponentFactory.createEquipment(invalid as EquipmentType)).toThrow();
  });

  it.each([0, -1, 0.5, NaN, Infinity, Number.MAX_SAFE_INTEGER + 1, '2', null])('rejects invalid level %j', level => {
    for (const type of Object.values(EquipmentType)) {
      expect(() => ShipComponentFactory.createEquipment(type, level as number)).toThrow();
    }
  });

  it.each([1, 2, 3, 4, 10])('preserves all six legacy equipment formulas at tier %i without silently clamping', level => {
    const cases = [
      { type: EquipmentType.WEAPON, slots: 2, weight: 30, cost: 2000, effect: { damage: 50 * level, range: 100 * level } },
      { type: EquipmentType.SHIELD, slots: 3, weight: 40, cost: 3000, effect: { protection: 100 * level, regenRate: 5 * level } },
      { type: EquipmentType.SCANNER, slots: 1, weight: 10, cost: 1500, effect: { range: 200 * level, accuracy: 80 + 5 * level } },
      { type: EquipmentType.MINING, slots: 4, weight: 60, cost: 4000, effect: { miningSpeed: 10 * level, efficiency: 70 + 10 * level } },
      { type: EquipmentType.REPAIR, slots: 2, weight: 25, cost: 2500, effect: { repairRate: 5 * level } },
      { type: EquipmentType.CARGO_EXPANSION, slots: 2, weight: 20, cost: 1000, effect: { bonusCapacity: 50 * level } }
    ];
    for (const item of cases) {
      const module = ShipComponentFactory.createEquipment(item.type, level);
      expect(module).toMatchObject({ type: item.type, slotsRequired: item.slots,
        weight: item.weight * level, cost: item.cost * level, effect: item.effect });
      expect(module.name).toContain(`Mk${level}`);
    }
    expect(ShipComponentFactory.createEquipment(EquipmentType.WEAPON).weight).toBe(30);
  });
});

describe('canonical flight factory', () => {
  it.each(['scout', 'freighter', 'miner'] as const)('creates %s without any legacy component factory calls', kind => {
    const power = vi.spyOn(LegacyShipComponentFactory, 'createPowerSource');
    const engine = vi.spyOn(LegacyShipComponentFactory, 'createEngine');
    const cargo = vi.spyOn(LegacyShipComponentFactory, 'createCargoHold');
    const equipment = vi.spyOn(LegacyShipComponentFactory, 'createEquipment');
    const design = createCivilianDesign(kind);
    const ship = ShipFactory.createFromDesign(design, 'test');
    expect(ship).toBeInstanceOf(DesignedShip);
    expect(ship.factionId).toBe('test');
    expect(ship.getDesign()).toEqual(design);
    expect(ship.getTotalWeight()).toBe(calculateShipStats(design).mass);
    expect(ship.getState().weapons).toEqual([]);
    expect(() => CombatShipFactory.createFromDesign(design, 'test')).toThrow('оружие');
    expect(power).not.toHaveBeenCalled(); expect(engine).not.toHaveBeenCalled();
    expect(cargo).not.toHaveBeenCalled(); expect(equipment).not.toHaveBeenCalled();
  });

  it('validates flight designs, refuses legacy objects and creates detached full runtime state', () => {
    expect(() => ShipFactory.createFromDesign(createDesign())).toThrow('двигатель');
    expect(() => ShipFactory.createFromDesign(makeLegacy() as unknown as ShipDesign)).toThrow();
    const design = createCivilianDesign('scout');
    const first = ShipFactory.createFromDesign(design), second = ShipFactory.createFromDesign(design);
    expect(first.factionId).toBe('neutral');
    expect(first.id).not.toBe(second.id);
    design.slots[3].component!.name = 'Changed';
    first.consumeEnergy(10);
    first.loadCargo({ resourceType: 'ore', amount: 10, weight: 20, volume: 10 });
    expect(first.getInstalledModuleNames()).not.toContain('Changed');
    expect(second.getState().cargo).toEqual([]);
    expect(second.getState().energy).toBe(calculateShipStats(second.getDesign()).energyCapacity);
  });

  it('routes civilian presets through the shared flight entry point', () => {
    const create = vi.spyOn(ShipFactory, 'createFromDesign');
    ShipFactory.createScout(); ShipFactory.createFreighter(); ShipFactory.createMiner();
    expect(create.mock.calls.map(([design]) => design.name)).toEqual(['Разведчик', 'Грузовоз', 'Добытчик']);
  });
});